spring.application.name=mail

server.port = 8084


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaishnavisrivastava.mail@gmail.com
#Password will be when you do two step authentication on your gmail. It will show password just once. Copy it and paste it here!
spring.mail.password=yjkk lmxr ifib nofg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Eureaka discovery client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=mail-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust package containing your event class
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Event class for deserialization
spring.kafka.consumer.properties.spring.json.value.default.type=com.myorganisation.mail.dto.UserCreatedEvent