spring.application.name=api-gateway


server.port=8080

# Eureka Service configuration (Discovery)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Route: Forward /api-gateway/user-service/ to lb://user-service using dynamic discovery
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api-gateway/user-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api-gateway/user-service/(?<segment>.*), /${segment}

# Route: Forward /api-gateway/product-service/ to lb://product-service using dynamic discovery
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api-gateway/product-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/api-gateway/product-service/(?<segment>.*), /${segment}

# Route: Forward /api-gateway/product-service/ to lb://product-service using dynamic discovery
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api-gateway/order-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/api-gateway/order-service/(?<segment>.*), /${segment}


